---
- name: check if azure-blob-storage-desktop is installed
  become: yes
  stat:
    path: '{{ azure_blob_storage_install_dir }}'
  register: azure_blob_storage_installed

- name: Download azure-blob-storage-desktop package
  get_url:
    url: '{{ azure_blob_storage_url }}'
    dest: '{{ azure_blob_storage_download_dir }}/{{ azure_blob_storage_filename }}'
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'
  when: azure_blob_storage_installed.stat.exists == 0

- name: Creates directory
  file:
    path: '{{ azure_blob_storage_install_dir }}'
    state: directory

- name: Install azure-blob-storage-desktop
  unarchive:
    src: '{{ azure_blob_storage_download_dir }}/{{ azure_blob_storage_filename }}'
    remote_src: yes
    dest: '{{ azure_blob_storage_install_dir }}'
    extra_opts:
      - '--strip-components=1'
    owner: root
    group: root
    creates: '{{ azure_blob_storage_install_dir }}/azure-blob-storage'
  when: azure_blob_storage_installed.stat.exists == 0

- name: "Copy default azure-blob-storage config for user {{ ansible_env.USER }}"
  copy:
    src: 'azure-blob-storage'
    dest: '{{ ansible_env.HOME }}/.local/share/applications/AzureBlobStorage.desktop'
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    force: no

- name: Remove downloaded package
  file: path={{ azure_blob_storage_download_dir }}/{{ azure_blob_storage_filename }} state=absent
  when: azure_blob_storage_installed.stat.exists == 0
